--- !ruby/object:Jumpstart::Configuration
application_name: Test App
business_name: Test App Company, LLC
domain: example.com
support_email: orourkeconn@yahoo.com
default_from_email: Jumpstart <support@example.com>
business_address: 201 Piermont Rd, Apt 1, Cresskill NJ 07626
background_job_processor: async
email_provider: ''
personal_accounts: true
livereload: true
solargraph: true
register_with_account: false
